version: '2'
services:
  bowling_board-app:
    image: bowling_board
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bowling_board-postgresql:5432/bowling_board
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  bowling_board-postgresql:
    extends:
      file: postgresql.yml
      service: bowling_board-postgresql
